name: wrestling_hub
description: "Wrestling Hub"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  #architecture
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  #Navigation
  go_router: ^14.3.0
  #network
  retrofit: ^4.4.0
  #data
  intl: ^0.19.0
  equatable: ^2.0.5
  shared_preferences: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  #support
  share_plus: ^10.0.3
  url_launcher: ^6.3.0
  fluttertoast: ^8.2.8
  logger: ^2.4.0
  #firebase
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  #ui
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.2.0+3
  flutter_inappwebview: ^6.1.5
  pinput: ^5.0.0
  image_picker: ^1.1.2
  widget_zoom: ^0.0.4
  flutter_multi_formatter: ^2.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Crimson
      fonts:
        - asset: assets/fonts/crimson/CrimsonText-Bold.ttf
        - asset: assets/fonts/crimson/CrimsonText-BoldItalic.ttf
        - asset: assets/fonts/crimson/CrimsonText-Italic.ttf
        - asset: assets/fonts/crimson/CrimsonText-Regular.ttf
        - asset: assets/fonts/crimson/CrimsonText-SemiBold.ttf
        - asset: assets/fonts/crimson/CrimsonText-SemiBoldItalic.ttf

